CREATE TABLE note (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content TEXT
);


CREATE TABLE USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);
CREATE TABLE AUTHORITIES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTHORITY VARCHAR(255) NOT NULL
);